//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedUtl4_TestStand.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedUtl4_TestStand.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified test index, {0}, is too high.{2}Valid values are positive integers less than {1}..
        /// </summary>
        internal static string ERRMSG_INVALID_TEST_INDEX {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_TEST_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string ERRMSG_LITERAL_ERROR {
            get {
                return ResourceManager.GetString("ERRMSG_LITERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application terminated with a run-time exception..
        /// </summary>
        internal static string ERRMSG_RUNTIME {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application ran without errors..
        /// </summary>
        internal static string ERRMSG_SUCCESS {
            get {
                return ResourceManager.GetString("ERRMSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character {0} ({1}): Display Value = {2}{3}.
        /// </summary>
        internal static string IDS_ASCII_TABLE_ITEM {
            get {
                return ResourceManager.GetString("IDS_ASCII_TABLE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The following table lists key attributes of every ASCII character.{0}.
        /// </summary>
        internal static string IDS_ASCII_TABLE_PREAMBLE {
            get {
                return ResourceManager.GetString("IDS_ASCII_TABLE_PREAMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the label row in the master input file is invalid.{3}It should contain {0} TAB delimited fields.{3}The supplied label contains {1} fields.{3}The label row follows.{2}{3}.
        /// </summary>
        internal static string IDS_BAD_MASTER_LABEL_ROW {
            get {
                return ResourceManager.GetString("IDS_BAD_MASTER_LABEL_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison must involve objects of the same type..
        /// </summary>
        internal static string IDS_COMPARETO_MISMATCH {
            get {
                return ResourceManager.GetString("IDS_COMPARETO_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Directory = {0}.
        /// </summary>
        internal static string IDS_DATA_DIRECTORY_NAME {
            get {
                return ResourceManager.GetString("IDS_DATA_DIRECTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source of Test Data.
        /// </summary>
        internal static string IDS_DATA_SOURCE {
            get {
                return ResourceManager.GetString("IDS_DATA_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Qualified Name of Input File.
        /// </summary>
        internal static string IDS_DATAFILE_FQFN {
            get {
                return ResourceManager.GetString("IDS_DATAFILE_FQFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Lines in Input File.
        /// </summary>
        internal static string IDS_DATAFILE_LINES {
            get {
                return ResourceManager.GetString("IDS_DATAFILE_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Input File Last Modified.
        /// </summary>
        internal static string IDS_DATAFILE_MODDATE {
            get {
                return ResourceManager.GetString("IDS_DATAFILE_MODDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size, in Bytes, of Input File.
        /// </summary>
        internal static string IDS_DATAFILE_SIZE {
            get {
                return ResourceManager.GetString("IDS_DATAFILE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master File.
        /// </summary>
        internal static string IDS_DESCR_MASTER_FILE {
            get {
                return ResourceManager.GetString("IDS_DESCR_MASTER_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Items File.
        /// </summary>
        internal static string IDS_DESCR_NEWITEMS_FILE {
            get {
                return ResourceManager.GetString("IDS_DESCR_NEWITEMS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        internal static string IDS_DESCR_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("IDS_DESCR_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input files are inconsistent{2}Label row of master file = {0}{2}Label Row of current file = {1}.
        /// </summary>
        internal static string IDS_INCONSISTENT_INPUTS {
            get {
                return ResourceManager.GetString("IDS_INCONSISTENT_INPUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key field {0} in record {1} is invalid. All keys must be integers..
        /// </summary>
        internal static string IDS_INVALID_KEY {
            get {
                return ResourceManager.GetString("IDS_INVALID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of Longest Line.
        /// </summary>
        internal static string IDS_LENGTH_OF_LONGEST {
            get {
                return ResourceManager.GetString("IDS_LENGTH_OF_LONGEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Begin Tests of MaxStringLength Method:{0}.
        /// </summary>
        internal static string IDS_MAX_STRLEN_BEGIN {
            get {
                return ResourceManager.GetString("IDS_MAX_STRLEN_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}MaxStringLength tests completed{0}.
        /// </summary>
        internal static string IDS_MAX_STRLEN_END {
            get {
                return ResourceManager.GetString("IDS_MAX_STRLEN_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Begin Tests of MergeNewItemsIntoArray Method:{0}.
        /// </summary>
        internal static string IDS_MERGENEWITEMSINTOARRAY_BEGIN {
            get {
                return ResourceManager.GetString("IDS_MERGENEWITEMSINTOARRAY_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}MergeNewItemsIntoArray tests completed{0}.
        /// </summary>
        internal static string IDS_MERGENEWITEMSINTOARRAY_END {
            get {
                return ResourceManager.GetString("IDS_MERGENEWITEMSINTOARRAY_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description\tFileName\tModDate\tSize\tLineCount.
        /// </summary>
        internal static string IDS_MERGENEWITEMSINTOARRAY_LABELS {
            get {
                return ResourceManager.GetString("IDS_MERGENEWITEMSINTOARRAY_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}{0} {1}{2}.
        /// </summary>
        internal static string IDS_MSG_BATCH {
            get {
                return ResourceManager.GetString("IDS_MSG_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string IDS_MSG_BEGIN {
            get {
                return ResourceManager.GetString("IDS_MSG_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string IDS_MSG_DONE {
            get {
                return ResourceManager.GetString("IDS_MSG_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string IDS_MSG_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_MSG_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Label = {0}.
        /// </summary>
        internal static string IDS_MSG_LONGEST_LABEL {
            get {
                return ResourceManager.GetString("IDS_MSG_LONGEST_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Value = {0}{1}.
        /// </summary>
        internal static string IDS_MSG_LONGEST_VALUE {
            get {
                return ResourceManager.GetString("IDS_MSG_LONGEST_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 1.
        /// </summary>
        internal static string IDS_MSG_REPORT_LABEL_1 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 2.
        /// </summary>
        internal static string IDS_MSG_REPORT_LABEL_2 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 3 Is Longer.
        /// </summary>
        internal static string IDS_MSG_REPORT_LABEL_3 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 4 Shorter.
        /// </summary>
        internal static string IDS_MSG_REPORT_LABEL_4 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Label 5.
        /// </summary>
        internal static string IDS_MSG_REPORT_LABEL_5 {
            get {
                return ResourceManager.GetString("IDS_MSG_REPORT_LABEL_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This long string is for testing another routine, for use in right-alingining numeric values in a report..
        /// </summary>
        internal static string IDS_REALLY_LONG_STRING {
            get {
                return ResourceManager.GetString("IDS_REALLY_LONG_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Test # {0}:{1}.
        /// </summary>
        internal static string IDS_TEST_BEGIN {
            get {
                return ResourceManager.GetString("IDS_TEST_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}    Test # {0} done{1}.
        /// </summary>
        internal static string IDS_TEST_END {
            get {
                return ResourceManager.GetString("IDS_TEST_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        internal static string IDS_TEST_FAIL {
            get {
                return ResourceManager.GetString("IDS_TEST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string IDS_TEST_PASS {
            get {
                return ResourceManager.GetString("IDS_TEST_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal variable _enmDataSource has an unsupported value of {0}.
        /// </summary>
        internal static string IDS_UNSUPPORTED_DATASOURCE {
            get {
                return ResourceManager.GetString("IDS_UNSUPPORTED_DATASOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Total exceptions logged = {0}.
        /// </summary>
        internal static string MSG_EXCETIONS_COUNTED {
            get {
                return ResourceManager.GetString("MSG_EXCETIONS_COUNTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Details for error {0}: .
        /// </summary>
        internal static string MSG_FORMAT_ERROR_DETAILS {
            get {
                return ResourceManager.GetString("MSG_FORMAT_ERROR_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}Case {0} of {1}:{2}.
        /// </summary>
        internal static string MSG_NEW_TEST {
            get {
                return ResourceManager.GetString("MSG_NEW_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Argument penmAlignment, a Alignment.
        /// </summary>
        internal static string MSG_PENMALIGNMENT {
            get {
                return ResourceManager.GetString("MSG_PENMALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Argument pstrFormatString, a string.
        /// </summary>
        internal static string MSG_PSTRFORMATSTRING {
            get {
                return ResourceManager.GetString("MSG_PSTRFORMATSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Argument puintItemIndex, a uint.
        /// </summary>
        internal static string MSG_PUINTITEMINDEX {
            get {
                return ResourceManager.GetString("MSG_PUINTITEMINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Argument puintMaximumWidth, a uint.
        /// </summary>
        internal static string MSG_PUINTMAXIMUMWIDTH {
            get {
                return ResourceManager.GetString("MSG_PUINTMAXIMUMWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The DisplayOrder properties are auto-generated.{0}.
        /// </summary>
        internal static string MSG_REPORT_DETAILS_AUTO_ORDERED {
            get {
                return ResourceManager.GetString("MSG_REPORT_DETAILS_AUTO_ORDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The DisplayOrder properties of selected items were explicitly set.{0}.
        /// </summary>
        internal static string MSG_REPORT_DETAILS_SELECTIVELY_OVERRIDDEN {
            get {
                return ResourceManager.GetString("MSG_REPORT_DETAILS_SELECTIVELY_OVERRIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The test collection is sorted.{0}.
        /// </summary>
        internal static string MSG_REPORT_DETAILS_SORTED {
            get {
                return ResourceManager.GetString("MSG_REPORT_DETAILS_SORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The test collection is UNsorted.{0}.
        /// </summary>
        internal static string MSG_REPORT_DETAILS_UNSORTED {
            get {
                return ResourceManager.GetString("MSG_REPORT_DETAILS_UNSORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token 0 = {0}, Token 1 ={1}, Token 2 - {2}, Token 3 = {3}.
        /// </summary>
        internal static string MSG_SAMPLE_FORMAT_STRING {
            get {
                return ResourceManager.GetString("MSG_SAMPLE_FORMAT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}    Sample Format: Before Transformation = {0}{2}                   After Transformation  = {1}{2}.
        /// </summary>
        internal static string MSG_SHOW_SAMPLE_BEFORE_AND_AFTER {
            get {
                return ResourceManager.GetString("MSG_SHOW_SAMPLE_BEFORE_AND_AFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Upgraded Format String.
        /// </summary>
        internal static string MSG_UPGRADED_FORMAT {
            get {
                return ResourceManager.GetString("MSG_UPGRADED_FORMAT", resourceCulture);
            }
        }
    }
}
