//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedUtl4_TestStand.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\DAVE\\Documents\\Visual Studio 2013\\Projects\\WizardWrx_Libs\\SharedUtl4\\Tes" +
            "t_Data\\")]
        public string Data_Directory {
            get {
                return ((string)(this["Data_Directory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaxStringLength.TXT")]
        public string MaxStringLength_Input {
            get {
                return ((string)(this["MaxStringLength_Input"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MergeNewItemsIntoArray_Master.TXT")]
        public string MergeNewItemsIntoArray_Master {
            get {
                return ((string)(this["MergeNewItemsIntoArray_Master"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MergeNewItemsIntoArray_Case_??.TXT")]
        public string MergeNewItemsIntoArray_Cases {
            get {
                return ((string)(this["MergeNewItemsIntoArray_Cases"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$DATADIRNAME$$\\MergeNewItemsIntoArray_Output_$$CASENBR$$.TXT")]
        public string MergeNewItemsIntoArray_Outputs {
            get {
                return ((string)(this["MergeNewItemsIntoArray_Outputs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MergeNewItemsIntoArray_Summary.TXT")]
        public string MergeNewItemsIntoArray_Summary {
            get {
                return ((string)(this["MergeNewItemsIntoArray_Summary"]));
            }
        }
    }
}
