//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The CreateFormatString method cannot process the specified format string.{1}    Specified format string = {0}.
        /// </summary>
        internal static string ERRMSG_CANNOT_PARSE {
            get {
                return ResourceManager.GetString("ERRMSG_CANNOT_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and.
        /// </summary>
        internal static string ERRMSG_COMMA_AND_LITERAL {
            get {
                return ResourceManager.GetString("ERRMSG_COMMA_AND_LITERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The specified object is a {0}.{2}Type must be {1}.
        /// </summary>
        internal static string ERRMSG_COMPARAND_IS_WRONG_TYPE {
            get {
                return ResourceManager.GetString("ERRMSG_COMPARAND_IS_WRONG_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The DetailFormat property cannot be a null reference or empty string..
        /// </summary>
        internal static string ERRMSG_DETAIL_FORMAT_CANNOT_BE_NULL_OR_BLANK {
            get {
                return ResourceManager.GetString("ERRMSG_DETAIL_FORMAT_CANNOT_BE_NULL_OR_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The DisplayOrder property cannot be set to zero..
        /// </summary>
        internal static string ERRMSG_DISPLAY_ORDER_CANNOT_BE_ZERO {
            get {
                return ResourceManager.GetString("ERRMSG_DISPLAY_ORDER_CANNOT_BE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} cannot be found in assembly {1}..
        /// </summary>
        internal static string ERRMSG_EMBEDDED_RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_EMBEDDED_RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading a file from resources embedded in the assembly.{3}Internal Name = {0}{3}File Length (bytes) = {1}{3}Bytes successfully read = {2}.
        /// </summary>
        internal static string ERRMSG_EMBEDDED_RESOURCE_READ_ERROR {
            get {
                return ResourceManager.GetString("ERRMSG_EMBEDDED_RESOURCE_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: No value has been assigned to this object..
        /// </summary>
        internal static string ERRMSG_REPORT_ITEM_IS_NULL {
            get {
                return ResourceManager.GetString("ERRMSG_REPORT_ITEM_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: This detail object is incomplete. It needs a label..
        /// </summary>
        internal static string ERRMSG_REPORT_ITEM_IS_UNLABELED {
            get {
                return ResourceManager.GetString("ERRMSG_REPORT_ITEM_IS_UNLABELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Label property of a ReportDetail cannot be null or blank..
        /// </summary>
        internal static string ERRMSG_SPECIFIED_LABEL_IS_NULL_OR_BLANK {
            get {
                return ResourceManager.GetString("ERRMSG_SPECIFIED_LABEL_IS_NULL_OR_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting at character position {0}{1}{2}.
        /// </summary>
        internal static string ERRMSG_START_CHARACTER {
            get {
                return ResourceManager.GetString("ERRMSG_START_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The value of the report item labeled {0} has not been set..
        /// </summary>
        internal static string ERRMSG_THIS_REPORTITEM_IS_NULL {
            get {
                return ResourceManager.GetString("ERRMSG_THIS_REPORTITEM_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * UNLABELED *.
        /// </summary>
        internal static string ERRMSG_UNLABELED {
            get {
                return ResourceManager.GetString("ERRMSG_UNLABELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT ERROR: Specified input string {0}{2}             contains {1} unresolved environment variable.{2}.
        /// </summary>
        internal static string ERRMSG_UNRESLOVED_ENVIRONEMT_STRINGS {
            get {
                return ResourceManager.GetString("ERRMSG_UNRESLOVED_ENVIRONEMT_STRINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        internal static string ERRMSG_VARIABLE_LITERAL {
            get {
                return ResourceManager.GetString("ERRMSG_VARIABLE_LITERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than zero..
        /// </summary>
        internal static string INCREMENT_CANNOT_BE_ZERO {
            get {
                return ResourceManager.GetString("INCREMENT_CANNOT_BE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Property Value.
        /// </summary>
        internal static string INCREMENT_PROPERTY_VALUE {
            get {
                return ResourceManager.GetString("INCREMENT_PROPERTY_VALUE", resourceCulture);
            }
        }
    }
}
